from __future__ import annotations


AUDIO_TUNING_SPECS: tuple[dict[str, object], ...] = (
    {
        "key": "chunk_ms",
        "label": "chunk_ms",
        "flag": "--chunk-ms",
        "default": "20",
        "type": "int",
        "min": 10,
        "max": 60,
        "unit": "ms",
        "desc": "Microphone frame length per chunk.",
    },
    {
        "key": "queue_size",
        "label": "queue_size",
        "flag": "--queue-size",
        "default": "128",
        "type": "int",
        "min": 64,
        "max": 512,
        "unit": "chunks",
        "desc": "Send queue capacity.",
    },
    {
        "key": "aec_ref_delay_ms",
        "label": "aec_ref_delay_ms",
        "flag": "--aec-ref-delay-ms",
        "default": "160",
        "type": "int",
        "min": 0,
        "max": 500,
        "unit": "ms",
        "desc": "Manual AEC reference delay compensation.",
    },
    {
        "key": "aec_max_suppress_gain",
        "label": "aec_max_suppress_gain",
        "flag": "--aec-max-suppress-gain",
        "default": "1.6",
        "type": "float",
        "min": 1.0,
        "max": 3.0,
        "unit": "ratio",
        "desc": "Upper limit for suppression gain.",
    },
    {
        "key": "aec_near_end_protect_ratio",
        "label": "aec_near_end_protect_ratio",
        "flag": "--aec-near-end-protect-ratio",
        "default": "1.16",
        "type": "float",
        "min": 1.0,
        "max": 1.5,
        "unit": "ratio",
        "desc": "Near-end voice protection ratio.",
    },
    {
        "key": "aec_tts_warmup_mute_ms",
        "label": "aec_tts_warmup_mute_ms",
        "flag": "--aec-tts-warmup-mute-ms",
        "default": "20",
        "type": "int",
        "min": 0,
        "max": 300,
        "unit": "ms",
        "desc": "Mute window right after TTS starts.",
    },
    {
        "key": "aec_tts_ref_wait_mute_ms",
        "label": "aec_tts_ref_wait_mute_ms",
        "flag": "--aec-tts-ref-wait-mute-ms",
        "default": "600",
        "type": "int",
        "min": 200,
        "max": 3000,
        "unit": "ms",
        "desc": "Mute window while waiting for reference signal.",
    },
    {
        "key": "aec_auto_delay_min_score",
        "label": "aec_auto_delay_min_score",
        "flag": "--aec-auto-delay-min-score",
        "default": "0.22",
        "type": "float",
        "min": 0.0,
        "max": 1.0,
        "unit": "ratio",
        "desc": "Minimum score threshold for auto delay update.",
    },
    {
        "key": "aec_search_span_ms",
        "label": "aec_search_span_ms",
        "flag": "--aec-search-span-ms",
        "default": "260",
        "type": "int",
        "min": 0,
        "max": 1000,
        "unit": "ms",
        "desc": "Search span for delay estimation.",
    },
    {
        "key": "aec_auto_delay_interval_chunks",
        "label": "aec_auto_delay_interval_chunks",
        "flag": "--aec-auto-delay-interval-chunks",
        "default": "4",
        "type": "int",
        "min": 1,
        "max": 32,
        "unit": "chunks",
        "desc": "Chunk interval for auto delay updates.",
    },
    {
        "key": "aec_adapt_alpha",
        "label": "aec_adapt_alpha",
        "flag": "--aec-adapt-alpha",
        "default": "0.35",
        "type": "float",
        "min": 0.0,
        "max": 1.0,
        "unit": "ratio",
        "desc": "Smoothing factor for adaptive delay update.",
    },
    {
        "key": "aec_ref_min_rms",
        "label": "aec_ref_min_rms",
        "flag": "--aec-ref-min-rms",
        "default": "400",
        "type": "float",
        "min": 0.0,
        "max": 5000.0,
        "unit": "rms",
        "desc": "Minimum reference RMS to trigger adaptation.",
    },
)

ASR_FIRST_PROFILE_OVERRIDES: dict[str, str] = {
    "queue_size": "128",
    "aec_ref_delay_ms": "160",
    "aec_max_suppress_gain": "1.6",
    "aec_near_end_protect_ratio": "1.16",
    "aec_tts_warmup_mute_ms": "20",
    "aec_tts_ref_wait_mute_ms": "600",
    "aec_auto_delay_min_score": "0.22",
    "aec_search_span_ms": "260",
    "aec_auto_delay_interval_chunks": "4",
    "aec_adapt_alpha": "0.35",
    "aec_ref_min_rms": "400",
}

AGGRESSIVE_PROFILE_OVERRIDES: dict[str, str] = {
    "aec_max_suppress_gain": "2.4",
    "aec_near_end_protect_ratio": "1.18",
    "aec_tts_warmup_mute_ms": "120",
    "aec_tts_ref_wait_mute_ms": "2200",
    "aec_auto_delay_min_score": "0.24",
    "aec_search_span_ms": "320",
    "aec_auto_delay_interval_chunks": "3",
    "aec_adapt_alpha": "0.45",
    "aec_ref_min_rms": "500",
}

RUNTIME_AUDIO_CONFIG_FILENAME = "_ui_audio_config.json"
